version = 2
final_space = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'os'
    style = 'diamond'
    powerline_symbol = 'î‚´'
    leading_diamond = 'î‚¶'
    template = '{{.Icon}} '
    background = 'p:blue'
    foreground = 'p:white'
    Text = ''
    Duration = 0
    NameLength = 0


  [[blocks.segments]]
    type = 'path'
    style = 'powerline'
    powerline_symbol = 'î‚´'
    template = ' {{.Path}}'
    background = 'p:blue'
    foreground = 'p:text'
    Text = ''
    Duration = 0
    NameLength = 0

    [blocks.segments.properties]
      folder_icon = '..î—¾..'
      home_icon = '~'
      style = 'agnoster_short'

  # [[blocks.segments]]
  #   type = "git"
  #   style = "powerline"
  #   powerline_symbol = 'î‚´'
  #   foreground = "p:text"
  #   background = "p:green"
  #   background_templates = [
  #     "{{ if or (.Working.Changed) (.Staging.Changed) }}#FF0000{{ end }}",
  #     "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#FFCC80{{ end }}",
  #     "{{ if gt .Ahead 0 }}p:pink{{ end }}",
  #     "{{ if gt .Behind 0 }}#B388FB{{ end }}"
  #   ]
  #   template = "{{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }} ï„ {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }} ï† {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }} ïƒ‡ {{ .StashCount }}{{ end }}"
  #
  #   [properties]
  #   fetch_status = true
  #   fetch_upstream_icon = true
  #   source = "cli"
  #
  #     [properties.untracked_modes]
  #     "/Users/user/Projects/oh-my-posh/" = "no"
  #
  #     [properties.mapped_branches]
  #     "feat/*" = "ğŸš€ "
  #     "bug/*" = "ğŸ› "

  [[blocks.segments]]
    type = 'git'
    style = 'powerline'
    powerline_symbol = 'î‚´'
    template = ' {{ .HEAD }}'
    background = 'p:lavender'
    foreground = 'p:text'
    Text = ''
    Duration = 0
    NameLength = 0

    [blocks.segments.properties]
      branch_icon = 'îœ¥ '
      cherry_pick_icon = 'îŠ› '
      commit_icon = 'ï— '
      fetch_status = false
      fetch_upstream_icon = false
      merge_icon = 'îœ§ '
      no_commits_icon = 'ïƒƒ '
      rebase_icon = 'îœ¨ '
      revert_icon = 'ïƒ¢ '
      tag_icon = 'ï’ '
      display_status = true
      template = " .{{ branch }} "

    # Change background based on Git conditions

    [[blocks.segments.conditions]]
      condition = "has_branch"
      background = "p:white"

    [[blocks.segments.conditions]]
      condition = "has_staged_files"
      background = "#FFD700"

    [[blocks.segments.conditions]]
      condition = "has_unstaged_files"
      background = "p:blue"

    [[blocks.segments.conditions]]
      condition = "has_untracked_files"
      background = "#00FF00"

    [[blocks.segments.conditions]]
      condition = "is_clean"
      background = "#00FF7F"

    [[blocks.segments.conditions]]
      condition = "has_conflicts"
      background = "#FF0000"

[palette]
  blue = '#8AADF4'
  lavender = '#B7BDF8'
  os = '#ACB0BE'
  pink = '#F5BDE6'
  text = '#494D64'
  white = '#FFFFFF'
  green = '#A6DA95'
